### ISSUE TITLE
[domain]  annotate dosing of a parent compound

### ISSUE THREAD

**Issue by ningyifan** [dbmi-pitt/dbmi-annotator#167]
we need to have a way to relate dosing of a parent compound to 1) enantiomers (if racemic) or 2) if the thing being annotated is a metabolite

example:  In the PMC2686909 R- Warfarin and S-Warfarin two forms of warfarin are mentioned with Pharmacokinetic data.

**Comment by ningyifan** [comment]
Applying OWL API before import to Postgres mpevidence schema to specify method value. 
Add two checkboxes for res.\* and parent compound.

**Comment by rkboyce** [comment]
This might be as simple as two additional radio buttons next to "drug 1" and "drug 2" when a claim is created. One radio button would be labeled "enantiomer" and the other "metabolite"

**Comment by rkboyce** [comment]
We notice that the best sentence span for a claim might not have the individual enantiomer or metabolite selectable. So, we should probably add a small pencil icon by each drug so that the user could type in the string if needed. Here is an example sentence:

With paroxetine pre-treatmtent the area under the concentration time curve(AUC) of (+)-and (-)-tramadol was increased (37% [P.001] and 32% [P.002], respectively), and the correspondingAUCs of (+)- and (-)-M1 were decreased (67% [P.0004] and 40% [P.0008], respectively).
